// Code generated by MockGen. DO NOT EDIT.
// Source: domain.go

// Package authauthorize is a generated GoMock package.
package authauthorize

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataAuthAuthorizeV1Adapter is a mock of DataAuthAuthorizeV1Adapter interface.
type MockDataAuthAuthorizeV1Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataAuthAuthorizeV1AdapterMockRecorder
}

// MockDataAuthAuthorizeV1AdapterMockRecorder is the mock recorder for MockDataAuthAuthorizeV1Adapter.
type MockDataAuthAuthorizeV1AdapterMockRecorder struct {
	mock *MockDataAuthAuthorizeV1Adapter
}

// NewMockDataAuthAuthorizeV1Adapter creates a new mock instance.
func NewMockDataAuthAuthorizeV1Adapter(ctrl *gomock.Controller) *MockDataAuthAuthorizeV1Adapter {
	mock := &MockDataAuthAuthorizeV1Adapter{ctrl: ctrl}
	mock.recorder = &MockDataAuthAuthorizeV1AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataAuthAuthorizeV1Adapter) EXPECT() *MockDataAuthAuthorizeV1AdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataAuthAuthorizeV1Adapter) Create(arg0 context.Context, arg1 *AuthAuthorize) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataAuthAuthorizeV1AdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataAuthAuthorizeV1Adapter)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDataAuthAuthorizeV1Adapter) Delete(arg0 context.Context, arg1 *AuthAuthorize) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataAuthAuthorizeV1AdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataAuthAuthorizeV1Adapter)(nil).Delete), arg0, arg1)
}

// Read mocks base method.
func (m *MockDataAuthAuthorizeV1Adapter) Read(arg0 context.Context, arg1 *AuthAuthorize) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataAuthAuthorizeV1AdapterMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataAuthAuthorizeV1Adapter)(nil).Read), arg0, arg1)
}

// ReadAll mocks base method.
func (m *MockDataAuthAuthorizeV1Adapter) ReadAll(arg0 context.Context, arg1 *[]AuthAuthorize, arg2 AuthAuthorizeParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataAuthAuthorizeV1AdapterMockRecorder) ReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataAuthAuthorizeV1Adapter)(nil).ReadAll), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDataAuthAuthorizeV1Adapter) Update(arg0 context.Context, arg1 AuthAuthorize) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataAuthAuthorizeV1AdapterMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataAuthAuthorizeV1Adapter)(nil).Update), arg0, arg1)
}
