// Code generated by MockGen. DO NOT EDIT.
// Source: domain.go

// Package registerroute is a generated GoMock package.
package registerroute

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataRegisterRouteV1Adapter is a mock of DataRegisterRouteV1Adapter interface.
type MockDataRegisterRouteV1Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataRegisterRouteV1AdapterMockRecorder
}

// MockDataRegisterRouteV1AdapterMockRecorder is the mock recorder for MockDataRegisterRouteV1Adapter.
type MockDataRegisterRouteV1AdapterMockRecorder struct {
	mock *MockDataRegisterRouteV1Adapter
}

// NewMockDataRegisterRouteV1Adapter creates a new mock instance.
func NewMockDataRegisterRouteV1Adapter(ctrl *gomock.Controller) *MockDataRegisterRouteV1Adapter {
	mock := &MockDataRegisterRouteV1Adapter{ctrl: ctrl}
	mock.recorder = &MockDataRegisterRouteV1AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataRegisterRouteV1Adapter) EXPECT() *MockDataRegisterRouteV1AdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataRegisterRouteV1Adapter) Create(arg0 context.Context, arg1 *RegisterRoute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataRegisterRouteV1AdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataRegisterRouteV1Adapter)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDataRegisterRouteV1Adapter) Delete(arg0 context.Context, arg1 *RegisterRoute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataRegisterRouteV1AdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataRegisterRouteV1Adapter)(nil).Delete), arg0, arg1)
}

// Read mocks base method.
func (m *MockDataRegisterRouteV1Adapter) Read(arg0 context.Context, arg1 *RegisterRoute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataRegisterRouteV1AdapterMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataRegisterRouteV1Adapter)(nil).Read), arg0, arg1)
}

// ReadAll mocks base method.
func (m *MockDataRegisterRouteV1Adapter) ReadAll(arg0 context.Context, arg1 *[]RegisterRoute, arg2 RegisterRouteParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataRegisterRouteV1AdapterMockRecorder) ReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataRegisterRouteV1Adapter)(nil).ReadAll), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDataRegisterRouteV1Adapter) Update(arg0 context.Context, arg1 RegisterRoute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataRegisterRouteV1AdapterMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataRegisterRouteV1Adapter)(nil).Update), arg0, arg1)
}
