// Code generated by MockGen. DO NOT EDIT.
// Source: domain.go

// Package authrefresh is a generated GoMock package.
package authrefresh

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataAuthRefreshV1Adapter is a mock of DataAuthRefreshV1Adapter interface.
type MockDataAuthRefreshV1Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataAuthRefreshV1AdapterMockRecorder
}

// MockDataAuthRefreshV1AdapterMockRecorder is the mock recorder for MockDataAuthRefreshV1Adapter.
type MockDataAuthRefreshV1AdapterMockRecorder struct {
	mock *MockDataAuthRefreshV1Adapter
}

// NewMockDataAuthRefreshV1Adapter creates a new mock instance.
func NewMockDataAuthRefreshV1Adapter(ctrl *gomock.Controller) *MockDataAuthRefreshV1Adapter {
	mock := &MockDataAuthRefreshV1Adapter{ctrl: ctrl}
	mock.recorder = &MockDataAuthRefreshV1AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataAuthRefreshV1Adapter) EXPECT() *MockDataAuthRefreshV1AdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataAuthRefreshV1Adapter) Create(arg0 context.Context, arg1 *AuthRefresh) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataAuthRefreshV1AdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataAuthRefreshV1Adapter)(nil).Create), arg0, arg1)
}

// CycleRefreshToken mocks base method.
func (m *MockDataAuthRefreshV1Adapter) CycleRefreshToken(arg0 context.Context, arg1, arg2 AuthRefresh) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CycleRefreshToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CycleRefreshToken indicates an expected call of CycleRefreshToken.
func (mr *MockDataAuthRefreshV1AdapterMockRecorder) CycleRefreshToken(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CycleRefreshToken", reflect.TypeOf((*MockDataAuthRefreshV1Adapter)(nil).CycleRefreshToken), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockDataAuthRefreshV1Adapter) Delete(arg0 context.Context, arg1 *AuthRefresh) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataAuthRefreshV1AdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataAuthRefreshV1Adapter)(nil).Delete), arg0, arg1)
}

// Read mocks base method.
func (m *MockDataAuthRefreshV1Adapter) Read(arg0 context.Context, arg1 *AuthRefresh) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataAuthRefreshV1AdapterMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataAuthRefreshV1Adapter)(nil).Read), arg0, arg1)
}

// ReadAll mocks base method.
func (m *MockDataAuthRefreshV1Adapter) ReadAll(arg0 context.Context, arg1 *[]AuthRefresh, arg2 AuthRefreshParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataAuthRefreshV1AdapterMockRecorder) ReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataAuthRefreshV1Adapter)(nil).ReadAll), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDataAuthRefreshV1Adapter) Update(arg0 context.Context, arg1 AuthRefresh) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataAuthRefreshV1AdapterMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataAuthRefreshV1Adapter)(nil).Update), arg0, arg1)
}
