// Code generated by MockGen. DO NOT EDIT.
// Source: domain.go

// Package role is a generated GoMock package.
package role

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataRoleV1Adapter is a mock of DataRoleV1Adapter interface.
type MockDataRoleV1Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataRoleV1AdapterMockRecorder
}

// MockDataRoleV1AdapterMockRecorder is the mock recorder for MockDataRoleV1Adapter.
type MockDataRoleV1AdapterMockRecorder struct {
	mock *MockDataRoleV1Adapter
}

// NewMockDataRoleV1Adapter creates a new mock instance.
func NewMockDataRoleV1Adapter(ctrl *gomock.Controller) *MockDataRoleV1Adapter {
	mock := &MockDataRoleV1Adapter{ctrl: ctrl}
	mock.recorder = &MockDataRoleV1AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataRoleV1Adapter) EXPECT() *MockDataRoleV1AdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataRoleV1Adapter) Create(arg0 context.Context, arg1 *Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataRoleV1AdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataRoleV1Adapter)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDataRoleV1Adapter) Delete(arg0 context.Context, arg1 *Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataRoleV1AdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataRoleV1Adapter)(nil).Delete), arg0, arg1)
}

// Read mocks base method.
func (m *MockDataRoleV1Adapter) Read(arg0 context.Context, arg1 *Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataRoleV1AdapterMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataRoleV1Adapter)(nil).Read), arg0, arg1)
}

// ReadAll mocks base method.
func (m *MockDataRoleV1Adapter) ReadAll(arg0 context.Context, arg1 *[]Role, arg2 RoleParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataRoleV1AdapterMockRecorder) ReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataRoleV1Adapter)(nil).ReadAll), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDataRoleV1Adapter) Update(arg0 context.Context, arg1 Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataRoleV1AdapterMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataRoleV1Adapter)(nil).Update), arg0, arg1)
}
