// Code generated by MockGen. DO NOT EDIT.
// Source: domain.go

// Package loginreset is a generated GoMock package.
package loginreset

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataLoginResetV1Adapter is a mock of DataLoginResetV1Adapter interface.
type MockDataLoginResetV1Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataLoginResetV1AdapterMockRecorder
}

// MockDataLoginResetV1AdapterMockRecorder is the mock recorder for MockDataLoginResetV1Adapter.
type MockDataLoginResetV1AdapterMockRecorder struct {
	mock *MockDataLoginResetV1Adapter
}

// NewMockDataLoginResetV1Adapter creates a new mock instance.
func NewMockDataLoginResetV1Adapter(ctrl *gomock.Controller) *MockDataLoginResetV1Adapter {
	mock := &MockDataLoginResetV1Adapter{ctrl: ctrl}
	mock.recorder = &MockDataLoginResetV1AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataLoginResetV1Adapter) EXPECT() *MockDataLoginResetV1AdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataLoginResetV1Adapter) Create(arg0 context.Context, arg1 *LoginReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataLoginResetV1AdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataLoginResetV1Adapter)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDataLoginResetV1Adapter) Delete(arg0 context.Context, arg1 *LoginReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataLoginResetV1AdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataLoginResetV1Adapter)(nil).Delete), arg0, arg1)
}

// Read mocks base method.
func (m *MockDataLoginResetV1Adapter) Read(arg0 context.Context, arg1 *LoginReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataLoginResetV1AdapterMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataLoginResetV1Adapter)(nil).Read), arg0, arg1)
}

// ReadAll mocks base method.
func (m *MockDataLoginResetV1Adapter) ReadAll(arg0 context.Context, arg1 *[]LoginReset, arg2 LoginResetParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataLoginResetV1AdapterMockRecorder) ReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataLoginResetV1Adapter)(nil).ReadAll), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDataLoginResetV1Adapter) Update(arg0 context.Context, arg1 LoginReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataLoginResetV1AdapterMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataLoginResetV1Adapter)(nil).Update), arg0, arg1)
}
