// Code generated by MockGen. DO NOT EDIT.
// Source: domain.go

// Package authclientsecret is a generated GoMock package.
package authclientsecret

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataAuthClientSecretV1Adapter is a mock of DataAuthClientSecretV1Adapter interface.
type MockDataAuthClientSecretV1Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataAuthClientSecretV1AdapterMockRecorder
}

// MockDataAuthClientSecretV1AdapterMockRecorder is the mock recorder for MockDataAuthClientSecretV1Adapter.
type MockDataAuthClientSecretV1AdapterMockRecorder struct {
	mock *MockDataAuthClientSecretV1Adapter
}

// NewMockDataAuthClientSecretV1Adapter creates a new mock instance.
func NewMockDataAuthClientSecretV1Adapter(ctrl *gomock.Controller) *MockDataAuthClientSecretV1Adapter {
	mock := &MockDataAuthClientSecretV1Adapter{ctrl: ctrl}
	mock.recorder = &MockDataAuthClientSecretV1AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataAuthClientSecretV1Adapter) EXPECT() *MockDataAuthClientSecretV1AdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataAuthClientSecretV1Adapter) Create(arg0 context.Context, arg1 *AuthClientSecret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataAuthClientSecretV1AdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataAuthClientSecretV1Adapter)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDataAuthClientSecretV1Adapter) Delete(arg0 context.Context, arg1 *AuthClientSecret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataAuthClientSecretV1AdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataAuthClientSecretV1Adapter)(nil).Delete), arg0, arg1)
}

// Read mocks base method.
func (m *MockDataAuthClientSecretV1Adapter) Read(arg0 context.Context, arg1 *AuthClientSecret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataAuthClientSecretV1AdapterMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataAuthClientSecretV1Adapter)(nil).Read), arg0, arg1)
}

// ReadAll mocks base method.
func (m *MockDataAuthClientSecretV1Adapter) ReadAll(arg0 context.Context, arg1 *[]AuthClientSecret, arg2 AuthClientSecretParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataAuthClientSecretV1AdapterMockRecorder) ReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataAuthClientSecretV1Adapter)(nil).ReadAll), arg0, arg1, arg2)
}

// ReadByIdAndSecret mocks base method.
func (m *MockDataAuthClientSecretV1Adapter) ReadByIdAndSecret(arg0 context.Context, arg1 *AuthClientSecret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByIdAndSecret", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadByIdAndSecret indicates an expected call of ReadByIdAndSecret.
func (mr *MockDataAuthClientSecretV1AdapterMockRecorder) ReadByIdAndSecret(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByIdAndSecret", reflect.TypeOf((*MockDataAuthClientSecretV1Adapter)(nil).ReadByIdAndSecret), arg0, arg1)
}

// Update mocks base method.
func (m *MockDataAuthClientSecretV1Adapter) Update(arg0 context.Context, arg1 AuthClientSecret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataAuthClientSecretV1AdapterMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataAuthClientSecretV1Adapter)(nil).Update), arg0, arg1)
}
