// Code generated by MockGen. DO NOT EDIT.
// Source: domain.go

// Package authclient is a generated GoMock package.
package authclient

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataAuthClientV1Adapter is a mock of DataAuthClientV1Adapter interface.
type MockDataAuthClientV1Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataAuthClientV1AdapterMockRecorder
}

// MockDataAuthClientV1AdapterMockRecorder is the mock recorder for MockDataAuthClientV1Adapter.
type MockDataAuthClientV1AdapterMockRecorder struct {
	mock *MockDataAuthClientV1Adapter
}

// NewMockDataAuthClientV1Adapter creates a new mock instance.
func NewMockDataAuthClientV1Adapter(ctrl *gomock.Controller) *MockDataAuthClientV1Adapter {
	mock := &MockDataAuthClientV1Adapter{ctrl: ctrl}
	mock.recorder = &MockDataAuthClientV1AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataAuthClientV1Adapter) EXPECT() *MockDataAuthClientV1AdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataAuthClientV1Adapter) Create(arg0 context.Context, arg1 *AuthClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataAuthClientV1AdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataAuthClientV1Adapter)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDataAuthClientV1Adapter) Delete(arg0 context.Context, arg1 *AuthClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataAuthClientV1AdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataAuthClientV1Adapter)(nil).Delete), arg0, arg1)
}

// Read mocks base method.
func (m *MockDataAuthClientV1Adapter) Read(arg0 context.Context, arg1 *AuthClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataAuthClientV1AdapterMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataAuthClientV1Adapter)(nil).Read), arg0, arg1)
}

// ReadAll mocks base method.
func (m *MockDataAuthClientV1Adapter) ReadAll(arg0 context.Context, arg1 *[]AuthClient, arg2 AuthClientParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataAuthClientV1AdapterMockRecorder) ReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataAuthClientV1Adapter)(nil).ReadAll), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDataAuthClientV1Adapter) Update(arg0 context.Context, arg1 AuthClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataAuthClientV1AdapterMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataAuthClientV1Adapter)(nil).Update), arg0, arg1)
}
