// Code generated by MockGen. DO NOT EDIT.
// Source: domain.go

// Package tddate is a generated GoMock package.
package tddate

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockDataTdDateV1Adapter is a mock of DataTdDateV1Adapter interface.
type MockDataTdDateV1Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataTdDateV1AdapterMockRecorder
}

// MockDataTdDateV1AdapterMockRecorder is the mock recorder for MockDataTdDateV1Adapter.
type MockDataTdDateV1AdapterMockRecorder struct {
	mock *MockDataTdDateV1Adapter
}

// NewMockDataTdDateV1Adapter creates a new mock instance.
func NewMockDataTdDateV1Adapter(ctrl *gomock.Controller) *MockDataTdDateV1Adapter {
	mock := &MockDataTdDateV1Adapter{ctrl: ctrl}
	mock.recorder = &MockDataTdDateV1AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataTdDateV1Adapter) EXPECT() *MockDataTdDateV1AdapterMockRecorder {
	return m.recorder
}

// CheckSetHoldTime mocks base method.
func (m *MockDataTdDateV1Adapter) CheckSetHoldTime(arg0 context.Context, arg1 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSetHoldTime", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckSetHoldTime indicates an expected call of CheckSetHoldTime.
func (mr *MockDataTdDateV1AdapterMockRecorder) CheckSetHoldTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSetHoldTime", reflect.TypeOf((*MockDataTdDateV1Adapter)(nil).CheckSetHoldTime), arg0, arg1)
}

// Confirm mocks base method.
func (m *MockDataTdDateV1Adapter) Confirm(arg0 context.Context, arg1 TdDate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Confirm indicates an expected call of Confirm.
func (mr *MockDataTdDateV1AdapterMockRecorder) Confirm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockDataTdDateV1Adapter)(nil).Confirm), arg0, arg1)
}

// Create mocks base method.
func (m *MockDataTdDateV1Adapter) Create(arg0 context.Context, arg1 *TdDate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataTdDateV1AdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataTdDateV1Adapter)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDataTdDateV1Adapter) Delete(arg0 context.Context, arg1 *TdDate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataTdDateV1AdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataTdDateV1Adapter)(nil).Delete), arg0, arg1)
}

// GetCurrentDays mocks base method.
func (m *MockDataTdDateV1Adapter) GetCurrentDays(arg0 context.Context, arg1 *[]time.Time, arg2 TdDateParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentDays", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetCurrentDays indicates an expected call of GetCurrentDays.
func (mr *MockDataTdDateV1AdapterMockRecorder) GetCurrentDays(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentDays", reflect.TypeOf((*MockDataTdDateV1Adapter)(nil).GetCurrentDays), arg0, arg1, arg2)
}

// Read mocks base method.
func (m *MockDataTdDateV1Adapter) Read(arg0 context.Context, arg1 *TdDate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataTdDateV1AdapterMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataTdDateV1Adapter)(nil).Read), arg0, arg1)
}

// ReadAll mocks base method.
func (m *MockDataTdDateV1Adapter) ReadAll(arg0 context.Context, arg1 *[]TdDate, arg2 TdDateParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataTdDateV1AdapterMockRecorder) ReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataTdDateV1Adapter)(nil).ReadAll), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDataTdDateV1Adapter) Update(arg0 context.Context, arg1 TdDate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataTdDateV1AdapterMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataTdDateV1Adapter)(nil).Update), arg0, arg1)
}
