// Code generated by MockGen. DO NOT EDIT.
// Source: domain.go

// Package authclientcallback is a generated GoMock package.
package authclientcallback

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataAuthClientCallbackV1Adapter is a mock of DataAuthClientCallbackV1Adapter interface.
type MockDataAuthClientCallbackV1Adapter struct {
	ctrl     *gomock.Controller
	recorder *MockDataAuthClientCallbackV1AdapterMockRecorder
}

// MockDataAuthClientCallbackV1AdapterMockRecorder is the mock recorder for MockDataAuthClientCallbackV1Adapter.
type MockDataAuthClientCallbackV1AdapterMockRecorder struct {
	mock *MockDataAuthClientCallbackV1Adapter
}

// NewMockDataAuthClientCallbackV1Adapter creates a new mock instance.
func NewMockDataAuthClientCallbackV1Adapter(ctrl *gomock.Controller) *MockDataAuthClientCallbackV1Adapter {
	mock := &MockDataAuthClientCallbackV1Adapter{ctrl: ctrl}
	mock.recorder = &MockDataAuthClientCallbackV1AdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataAuthClientCallbackV1Adapter) EXPECT() *MockDataAuthClientCallbackV1AdapterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataAuthClientCallbackV1Adapter) Create(arg0 context.Context, arg1 *AuthClientCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataAuthClientCallbackV1AdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataAuthClientCallbackV1Adapter)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDataAuthClientCallbackV1Adapter) Delete(arg0 context.Context, arg1 *AuthClientCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataAuthClientCallbackV1AdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataAuthClientCallbackV1Adapter)(nil).Delete), arg0, arg1)
}

// Read mocks base method.
func (m *MockDataAuthClientCallbackV1Adapter) Read(arg0 context.Context, arg1 *AuthClientCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockDataAuthClientCallbackV1AdapterMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockDataAuthClientCallbackV1Adapter)(nil).Read), arg0, arg1)
}

// ReadAll mocks base method.
func (m *MockDataAuthClientCallbackV1Adapter) ReadAll(arg0 context.Context, arg1 *[]AuthClientCallback, arg2 AuthClientCallbackParam) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDataAuthClientCallbackV1AdapterMockRecorder) ReadAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDataAuthClientCallbackV1Adapter)(nil).ReadAll), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDataAuthClientCallbackV1Adapter) Update(arg0 context.Context, arg1 AuthClientCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataAuthClientCallbackV1AdapterMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataAuthClientCallbackV1Adapter)(nil).Update), arg0, arg1)
}
