// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/tithe-declare.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDIn) Reset() {
	*x = IDIn{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDIn) ProtoMessage() {}

func (x *IDIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDIn.ProtoReflect.Descriptor instead.
func (*IDIn) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{0}
}

func (x *IDIn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{2}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{3}
}

func (x *RoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RoleResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type RoleRepeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          []*Role                `protobuf:"bytes,1,rep,name=Role,proto3" json:"Role,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleRepeatResponse) Reset() {
	*x = RoleRepeatResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleRepeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRepeatResponse) ProtoMessage() {}

func (x *RoleRepeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRepeatResponse.ProtoReflect.Descriptor instead.
func (*RoleRepeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{4}
}

func (x *RoleRepeatResponse) GetRole() []*Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RoleRepeatResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type RoleIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleIDIn) Reset() {
	*x = RoleIDIn{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleIDIn) ProtoMessage() {}

func (x *RoleIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleIDIn.ProtoReflect.Descriptor instead.
func (*RoleIDIn) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{5}
}

func (x *RoleIDIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	EmailAddr     string                 `protobuf:"bytes,2,opt,name=EmailAddr,proto3" json:"EmailAddr,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Pwd           string                 `protobuf:"bytes,5,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=Active,proto3" json:"Active,omitempty"`
	SetPwd        bool                   `protobuf:"varint,7,opt,name=SetPwd,proto3" json:"SetPwd,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Login) Reset() {
	*x = Login{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{6}
}

func (x *Login) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Login) GetEmailAddr() string {
	if x != nil {
		return x.EmailAddr
	}
	return ""
}

func (x *Login) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Login) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Login) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *Login) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Login) GetSetPwd() bool {
	if x != nil {
		return x.SetPwd
	}
	return false
}

func (x *Login) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Login) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         *Login                 `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetLogin() *Login {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *LoginResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type LoginRepeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         []*Login               `protobuf:"bytes,1,rep,name=Login,proto3" json:"Login,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRepeatResponse) Reset() {
	*x = LoginRepeatResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRepeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRepeatResponse) ProtoMessage() {}

func (x *LoginRepeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRepeatResponse.ProtoReflect.Descriptor instead.
func (*LoginRepeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{8}
}

func (x *LoginRepeatResponse) GetLogin() []*Login {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *LoginRepeatResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type LoginIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginIDIn) Reset() {
	*x = LoginIDIn{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginIDIn) ProtoMessage() {}

func (x *LoginIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginIDIn.ProtoReflect.Descriptor instead.
func (*LoginIDIn) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{9}
}

func (x *LoginIDIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoginRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginId       string                 `protobuf:"bytes,1,opt,name=LoginId,proto3" json:"LoginId,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRole) Reset() {
	*x = LoginRole{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRole) ProtoMessage() {}

func (x *LoginRole) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRole.ProtoReflect.Descriptor instead.
func (*LoginRole) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{10}
}

func (x *LoginRole) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

func (x *LoginRole) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type LoginRoleUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginId       string                 `protobuf:"bytes,1,opt,name=LoginId,proto3" json:"LoginId,omitempty"`
	RoleIds       []string               `protobuf:"bytes,2,rep,name=RoleIds,proto3" json:"RoleIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRoleUpdate) Reset() {
	*x = LoginRoleUpdate{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRoleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRoleUpdate) ProtoMessage() {}

func (x *LoginRoleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRoleUpdate.ProtoReflect.Descriptor instead.
func (*LoginRoleUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{11}
}

func (x *LoginRoleUpdate) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

func (x *LoginRoleUpdate) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type LoginRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginRole     *LoginRole             `protobuf:"bytes,1,opt,name=LoginRole,proto3" json:"LoginRole,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRoleResponse) Reset() {
	*x = LoginRoleResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRoleResponse) ProtoMessage() {}

func (x *LoginRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRoleResponse.ProtoReflect.Descriptor instead.
func (*LoginRoleResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{12}
}

func (x *LoginRoleResponse) GetLoginRole() *LoginRole {
	if x != nil {
		return x.LoginRole
	}
	return nil
}

func (x *LoginRoleResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type LoginRoleUpdateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LoginRoleUpdate *LoginRoleUpdate       `protobuf:"bytes,1,opt,name=LoginRoleUpdate,proto3" json:"LoginRoleUpdate,omitempty"`
	Result          *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginRoleUpdateResponse) Reset() {
	*x = LoginRoleUpdateResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRoleUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRoleUpdateResponse) ProtoMessage() {}

func (x *LoginRoleUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRoleUpdateResponse.ProtoReflect.Descriptor instead.
func (*LoginRoleUpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{13}
}

func (x *LoginRoleUpdateResponse) GetLoginRoleUpdate() *LoginRoleUpdate {
	if x != nil {
		return x.LoginRoleUpdate
	}
	return nil
}

func (x *LoginRoleUpdateResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type LoginRoleRepeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginRole     []*LoginRole           `protobuf:"bytes,1,rep,name=LoginRole,proto3" json:"LoginRole,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRoleRepeatResponse) Reset() {
	*x = LoginRoleRepeatResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRoleRepeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRoleRepeatResponse) ProtoMessage() {}

func (x *LoginRoleRepeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRoleRepeatResponse.ProtoReflect.Descriptor instead.
func (*LoginRoleRepeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{14}
}

func (x *LoginRoleRepeatResponse) GetLoginRole() []*LoginRole {
	if x != nil {
		return x.LoginRole
	}
	return nil
}

func (x *LoginRoleRepeatResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type LoginRoleIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginId       string                 `protobuf:"bytes,1,opt,name=LoginId,proto3" json:"LoginId,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRoleIDIn) Reset() {
	*x = LoginRoleIDIn{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRoleIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRoleIDIn) ProtoMessage() {}

func (x *LoginRoleIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRoleIDIn.ProtoReflect.Descriptor instead.
func (*LoginRoleIDIn) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{15}
}

func (x *LoginRoleIDIn) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

func (x *LoginRoleIDIn) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type TdDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	DateValue     string                 `protobuf:"bytes,2,opt,name=DateValue,proto3" json:"DateValue,omitempty"`
	Hold          string                 `protobuf:"bytes,3,opt,name=Hold,proto3" json:"Hold,omitempty"`
	Confirm       string                 `protobuf:"bytes,4,opt,name=Confirm,proto3" json:"Confirm,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TdDate) Reset() {
	*x = TdDate{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TdDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TdDate) ProtoMessage() {}

func (x *TdDate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TdDate.ProtoReflect.Descriptor instead.
func (*TdDate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{16}
}

func (x *TdDate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TdDate) GetDateValue() string {
	if x != nil {
		return x.DateValue
	}
	return ""
}

func (x *TdDate) GetHold() string {
	if x != nil {
		return x.Hold
	}
	return ""
}

func (x *TdDate) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

func (x *TdDate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TdDate) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *TdDate) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TdDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TdDate        *TdDate                `protobuf:"bytes,1,opt,name=TdDate,proto3" json:"TdDate,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TdDateResponse) Reset() {
	*x = TdDateResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TdDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TdDateResponse) ProtoMessage() {}

func (x *TdDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TdDateResponse.ProtoReflect.Descriptor instead.
func (*TdDateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{17}
}

func (x *TdDateResponse) GetTdDate() *TdDate {
	if x != nil {
		return x.TdDate
	}
	return nil
}

func (x *TdDateResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type TdDateRepeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TdDate        []*TdDate              `protobuf:"bytes,1,rep,name=TdDate,proto3" json:"TdDate,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TdDateRepeatResponse) Reset() {
	*x = TdDateRepeatResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TdDateRepeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TdDateRepeatResponse) ProtoMessage() {}

func (x *TdDateRepeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TdDateRepeatResponse.ProtoReflect.Descriptor instead.
func (*TdDateRepeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{18}
}

func (x *TdDateRepeatResponse) GetTdDate() []*TdDate {
	if x != nil {
		return x.TdDate
	}
	return nil
}

func (x *TdDateRepeatResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type TdDateIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TdDateIDIn) Reset() {
	*x = TdDateIDIn{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TdDateIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TdDateIDIn) ProtoMessage() {}

func (x *TdDateIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TdDateIDIn.ProtoReflect.Descriptor instead.
func (*TdDateIDIn) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{19}
}

func (x *TdDateIDIn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmailReminder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailReminder) Reset() {
	*x = EmailReminder{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailReminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReminder) ProtoMessage() {}

func (x *EmailReminder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReminder.ProtoReflect.Descriptor instead.
func (*EmailReminder) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{20}
}

func (x *EmailReminder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmailReminder) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EmailReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailReminder *EmailReminder         `protobuf:"bytes,1,opt,name=EmailReminder,proto3" json:"EmailReminder,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailReminderResponse) Reset() {
	*x = EmailReminderResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReminderResponse) ProtoMessage() {}

func (x *EmailReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReminderResponse.ProtoReflect.Descriptor instead.
func (*EmailReminderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{21}
}

func (x *EmailReminderResponse) GetEmailReminder() *EmailReminder {
	if x != nil {
		return x.EmailReminder
	}
	return nil
}

func (x *EmailReminderResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type EmailReminderRepeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailReminder []*EmailReminder       `protobuf:"bytes,1,rep,name=EmailReminder,proto3" json:"EmailReminder,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailReminderRepeatResponse) Reset() {
	*x = EmailReminderRepeatResponse{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailReminderRepeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReminderRepeatResponse) ProtoMessage() {}

func (x *EmailReminderRepeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReminderRepeatResponse.ProtoReflect.Descriptor instead.
func (*EmailReminderRepeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{22}
}

func (x *EmailReminderRepeatResponse) GetEmailReminder() []*EmailReminder {
	if x != nil {
		return x.EmailReminder
	}
	return nil
}

func (x *EmailReminderRepeatResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type EmailReminderIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailReminderIDIn) Reset() {
	*x = EmailReminderIDIn{}
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailReminderIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReminderIDIn) ProtoMessage() {}

func (x *EmailReminderIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tithe_declare_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReminderIDIn.ProtoReflect.Descriptor instead.
func (*EmailReminderIDIn) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tithe_declare_proto_rawDescGZIP(), []int{23}
}

func (x *EmailReminderIDIn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_pkg_proto_tithe_declare_proto protoreflect.FileDescriptor

const file_pkg_proto_tithe_declare_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/tithe-declare.proto\x12\x05proto\"\x16\n" +
	"\x04IDIn\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"8\n" +
	"\x06Result\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"L\n" +
	"\x04Role\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\"V\n" +
	"\fRoleResponse\x12\x1f\n" +
	"\x04Role\x18\x01 \x01(\v2\v.proto.RoleR\x04Role\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"\\\n" +
	"\x12RoleRepeatResponse\x12\x1f\n" +
	"\x04Role\x18\x01 \x03(\v2\v.proto.RoleR\x04Role\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"\x1a\n" +
	"\bRoleIDIn\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"\xed\x01\n" +
	"\x05Login\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x1c\n" +
	"\tEmailAddr\x18\x02 \x01(\tR\tEmailAddr\x12\x1c\n" +
	"\tFirstName\x18\x03 \x01(\tR\tFirstName\x12\x1a\n" +
	"\bLastName\x18\x04 \x01(\tR\bLastName\x12\x10\n" +
	"\x03Pwd\x18\x05 \x01(\tR\x03Pwd\x12\x16\n" +
	"\x06Active\x18\x06 \x01(\bR\x06Active\x12\x16\n" +
	"\x06SetPwd\x18\a \x01(\bR\x06SetPwd\x12\x1c\n" +
	"\tCreatedAt\x18\b \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\t \x01(\tR\tUpdatedAt\"Z\n" +
	"\rLoginResponse\x12\"\n" +
	"\x05Login\x18\x01 \x01(\v2\f.proto.LoginR\x05Login\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"`\n" +
	"\x13LoginRepeatResponse\x12\"\n" +
	"\x05Login\x18\x01 \x03(\v2\f.proto.LoginR\x05Login\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"\x1b\n" +
	"\tLoginIDIn\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"=\n" +
	"\tLoginRole\x12\x18\n" +
	"\aLoginId\x18\x01 \x01(\tR\aLoginId\x12\x16\n" +
	"\x06RoleId\x18\x02 \x01(\tR\x06RoleId\"E\n" +
	"\x0fLoginRoleUpdate\x12\x18\n" +
	"\aLoginId\x18\x01 \x01(\tR\aLoginId\x12\x18\n" +
	"\aRoleIds\x18\x02 \x03(\tR\aRoleIds\"j\n" +
	"\x11LoginRoleResponse\x12.\n" +
	"\tLoginRole\x18\x01 \x01(\v2\x10.proto.LoginRoleR\tLoginRole\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"\x82\x01\n" +
	"\x17LoginRoleUpdateResponse\x12@\n" +
	"\x0fLoginRoleUpdate\x18\x01 \x01(\v2\x16.proto.LoginRoleUpdateR\x0fLoginRoleUpdate\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"p\n" +
	"\x17LoginRoleRepeatResponse\x12.\n" +
	"\tLoginRole\x18\x01 \x03(\v2\x10.proto.LoginRoleR\tLoginRole\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"A\n" +
	"\rLoginRoleIDIn\x12\x18\n" +
	"\aLoginId\x18\x01 \x01(\tR\aLoginId\x12\x16\n" +
	"\x06RoleId\x18\x02 \x01(\tR\x06RoleId\"\xa4\x01\n" +
	"\x06TdDate\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x1c\n" +
	"\tDateValue\x18\x02 \x01(\tR\tDateValue\x12\x12\n" +
	"\x04Hold\x18\x03 \x01(\tR\x04Hold\x12\x18\n" +
	"\aConfirm\x18\x04 \x01(\tR\aConfirm\x12\x12\n" +
	"\x04Name\x18\x05 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Phone\x18\x06 \x01(\tR\x05Phone\x12\x14\n" +
	"\x05Email\x18\a \x01(\tR\x05Email\"^\n" +
	"\x0eTdDateResponse\x12%\n" +
	"\x06TdDate\x18\x01 \x01(\v2\r.proto.TdDateR\x06TdDate\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"d\n" +
	"\x14TdDateRepeatResponse\x12%\n" +
	"\x06TdDate\x18\x01 \x03(\v2\r.proto.TdDateR\x06TdDate\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"\x1c\n" +
	"\n" +
	"TdDateIDIn\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"5\n" +
	"\rEmailReminder\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\"z\n" +
	"\x15EmailReminderResponse\x12:\n" +
	"\rEmailReminder\x18\x01 \x01(\v2\x14.proto.EmailReminderR\rEmailReminder\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"\x80\x01\n" +
	"\x1bEmailReminderRepeatResponse\x12:\n" +
	"\rEmailReminder\x18\x01 \x03(\v2\x14.proto.EmailReminderR\rEmailReminder\x12%\n" +
	"\x06result\x18\x02 \x01(\v2\r.proto.ResultR\x06result\"#\n" +
	"\x11EmailReminderIDIn\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id2\xfc\x01\n" +
	"\vRoleService\x12/\n" +
	"\aGetRole\x12\x0f.proto.RoleIDIn\x1a\x13.proto.RoleResponse\x124\n" +
	"\n" +
	"SearchRole\x12\v.proto.Role\x1a\x19.proto.RoleRepeatResponse\x12.\n" +
	"\n" +
	"CreateRole\x12\v.proto.Role\x1a\x13.proto.RoleResponse\x12(\n" +
	"\n" +
	"UpdateRole\x12\v.proto.Role\x1a\r.proto.Result\x12,\n" +
	"\n" +
	"DeleteRole\x12\x0f.proto.RoleIDIn\x1a\r.proto.Result2\x8a\x02\n" +
	"\fLoginService\x122\n" +
	"\bGetLogin\x12\x10.proto.LoginIDIn\x1a\x14.proto.LoginResponse\x127\n" +
	"\vSearchLogin\x12\f.proto.Login\x1a\x1a.proto.LoginRepeatResponse\x121\n" +
	"\vCreateLogin\x12\f.proto.Login\x1a\x14.proto.LoginResponse\x12*\n" +
	"\vUpdateLogin\x12\f.proto.Login\x1a\r.proto.Result\x12.\n" +
	"\vDeleteLogin\x12\x10.proto.LoginIDIn\x1a\r.proto.Result2\x8b\x03\n" +
	"\x10LoginRoleService\x12>\n" +
	"\fGetLoginRole\x12\x14.proto.LoginRoleIDIn\x1a\x18.proto.LoginRoleResponse\x12C\n" +
	"\x0fSearchLoginRole\x12\x10.proto.LoginRole\x1a\x1e.proto.LoginRoleRepeatResponse\x12=\n" +
	"\x0fCreateLoginRole\x12\x10.proto.LoginRole\x1a\x18.proto.LoginRoleResponse\x12G\n" +
	"\rBulkLoginRole\x12\x16.proto.LoginRoleUpdate\x1a\x1e.proto.LoginRoleUpdateResponse\x122\n" +
	"\x0fUpdateLoginRole\x12\x10.proto.LoginRole\x1a\r.proto.Result\x126\n" +
	"\x0fDeleteLoginRole\x12\x14.proto.LoginRoleIDIn\x1a\r.proto.Result2\x98\x02\n" +
	"\rTdDateService\x125\n" +
	"\tGetTdDate\x12\x11.proto.TdDateIDIn\x1a\x15.proto.TdDateResponse\x12:\n" +
	"\fSearchTdDate\x12\r.proto.TdDate\x1a\x1b.proto.TdDateRepeatResponse\x124\n" +
	"\fCreateTdDate\x12\r.proto.TdDate\x1a\x15.proto.TdDateResponse\x12,\n" +
	"\fUpdateTdDate\x12\r.proto.TdDate\x1a\r.proto.Result\x120\n" +
	"\fDeleteTdDate\x12\x11.proto.TdDateIDIn\x1a\r.proto.Result2\xfa\x02\n" +
	"\x14EmailReminderService\x12J\n" +
	"\x10GetEmailReminder\x12\x18.proto.EmailReminderIDIn\x1a\x1c.proto.EmailReminderResponse\x12O\n" +
	"\x13SearchEmailReminder\x12\x14.proto.EmailReminder\x1a\".proto.EmailReminderRepeatResponse\x12I\n" +
	"\x13CreateEmailReminder\x12\x14.proto.EmailReminder\x1a\x1c.proto.EmailReminderResponse\x12:\n" +
	"\x13UpdateEmailReminder\x12\x14.proto.EmailReminder\x1a\r.proto.Result\x12>\n" +
	"\x13DeleteEmailReminder\x12\x18.proto.EmailReminderIDIn\x1a\r.proto.ResultB\rZ\v./;protobufb\x06proto3"

var (
	file_pkg_proto_tithe_declare_proto_rawDescOnce sync.Once
	file_pkg_proto_tithe_declare_proto_rawDescData []byte
)

func file_pkg_proto_tithe_declare_proto_rawDescGZIP() []byte {
	file_pkg_proto_tithe_declare_proto_rawDescOnce.Do(func() {
		file_pkg_proto_tithe_declare_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_tithe_declare_proto_rawDesc), len(file_pkg_proto_tithe_declare_proto_rawDesc)))
	})
	return file_pkg_proto_tithe_declare_proto_rawDescData
}

var file_pkg_proto_tithe_declare_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pkg_proto_tithe_declare_proto_goTypes = []any{
	(*IDIn)(nil),                        // 0: proto.IDIn
	(*Result)(nil),                      // 1: proto.Result
	(*Role)(nil),                        // 2: proto.Role
	(*RoleResponse)(nil),                // 3: proto.RoleResponse
	(*RoleRepeatResponse)(nil),          // 4: proto.RoleRepeatResponse
	(*RoleIDIn)(nil),                    // 5: proto.RoleIDIn
	(*Login)(nil),                       // 6: proto.Login
	(*LoginResponse)(nil),               // 7: proto.LoginResponse
	(*LoginRepeatResponse)(nil),         // 8: proto.LoginRepeatResponse
	(*LoginIDIn)(nil),                   // 9: proto.LoginIDIn
	(*LoginRole)(nil),                   // 10: proto.LoginRole
	(*LoginRoleUpdate)(nil),             // 11: proto.LoginRoleUpdate
	(*LoginRoleResponse)(nil),           // 12: proto.LoginRoleResponse
	(*LoginRoleUpdateResponse)(nil),     // 13: proto.LoginRoleUpdateResponse
	(*LoginRoleRepeatResponse)(nil),     // 14: proto.LoginRoleRepeatResponse
	(*LoginRoleIDIn)(nil),               // 15: proto.LoginRoleIDIn
	(*TdDate)(nil),                      // 16: proto.TdDate
	(*TdDateResponse)(nil),              // 17: proto.TdDateResponse
	(*TdDateRepeatResponse)(nil),        // 18: proto.TdDateRepeatResponse
	(*TdDateIDIn)(nil),                  // 19: proto.TdDateIDIn
	(*EmailReminder)(nil),               // 20: proto.EmailReminder
	(*EmailReminderResponse)(nil),       // 21: proto.EmailReminderResponse
	(*EmailReminderRepeatResponse)(nil), // 22: proto.EmailReminderRepeatResponse
	(*EmailReminderIDIn)(nil),           // 23: proto.EmailReminderIDIn
}
var file_pkg_proto_tithe_declare_proto_depIdxs = []int32{
	2,  // 0: proto.RoleResponse.Role:type_name -> proto.Role
	1,  // 1: proto.RoleResponse.result:type_name -> proto.Result
	2,  // 2: proto.RoleRepeatResponse.Role:type_name -> proto.Role
	1,  // 3: proto.RoleRepeatResponse.result:type_name -> proto.Result
	6,  // 4: proto.LoginResponse.Login:type_name -> proto.Login
	1,  // 5: proto.LoginResponse.result:type_name -> proto.Result
	6,  // 6: proto.LoginRepeatResponse.Login:type_name -> proto.Login
	1,  // 7: proto.LoginRepeatResponse.result:type_name -> proto.Result
	10, // 8: proto.LoginRoleResponse.LoginRole:type_name -> proto.LoginRole
	1,  // 9: proto.LoginRoleResponse.result:type_name -> proto.Result
	11, // 10: proto.LoginRoleUpdateResponse.LoginRoleUpdate:type_name -> proto.LoginRoleUpdate
	1,  // 11: proto.LoginRoleUpdateResponse.result:type_name -> proto.Result
	10, // 12: proto.LoginRoleRepeatResponse.LoginRole:type_name -> proto.LoginRole
	1,  // 13: proto.LoginRoleRepeatResponse.result:type_name -> proto.Result
	16, // 14: proto.TdDateResponse.TdDate:type_name -> proto.TdDate
	1,  // 15: proto.TdDateResponse.result:type_name -> proto.Result
	16, // 16: proto.TdDateRepeatResponse.TdDate:type_name -> proto.TdDate
	1,  // 17: proto.TdDateRepeatResponse.result:type_name -> proto.Result
	20, // 18: proto.EmailReminderResponse.EmailReminder:type_name -> proto.EmailReminder
	1,  // 19: proto.EmailReminderResponse.result:type_name -> proto.Result
	20, // 20: proto.EmailReminderRepeatResponse.EmailReminder:type_name -> proto.EmailReminder
	1,  // 21: proto.EmailReminderRepeatResponse.result:type_name -> proto.Result
	5,  // 22: proto.RoleService.GetRole:input_type -> proto.RoleIDIn
	2,  // 23: proto.RoleService.SearchRole:input_type -> proto.Role
	2,  // 24: proto.RoleService.CreateRole:input_type -> proto.Role
	2,  // 25: proto.RoleService.UpdateRole:input_type -> proto.Role
	5,  // 26: proto.RoleService.DeleteRole:input_type -> proto.RoleIDIn
	9,  // 27: proto.LoginService.GetLogin:input_type -> proto.LoginIDIn
	6,  // 28: proto.LoginService.SearchLogin:input_type -> proto.Login
	6,  // 29: proto.LoginService.CreateLogin:input_type -> proto.Login
	6,  // 30: proto.LoginService.UpdateLogin:input_type -> proto.Login
	9,  // 31: proto.LoginService.DeleteLogin:input_type -> proto.LoginIDIn
	15, // 32: proto.LoginRoleService.GetLoginRole:input_type -> proto.LoginRoleIDIn
	10, // 33: proto.LoginRoleService.SearchLoginRole:input_type -> proto.LoginRole
	10, // 34: proto.LoginRoleService.CreateLoginRole:input_type -> proto.LoginRole
	11, // 35: proto.LoginRoleService.BulkLoginRole:input_type -> proto.LoginRoleUpdate
	10, // 36: proto.LoginRoleService.UpdateLoginRole:input_type -> proto.LoginRole
	15, // 37: proto.LoginRoleService.DeleteLoginRole:input_type -> proto.LoginRoleIDIn
	19, // 38: proto.TdDateService.GetTdDate:input_type -> proto.TdDateIDIn
	16, // 39: proto.TdDateService.SearchTdDate:input_type -> proto.TdDate
	16, // 40: proto.TdDateService.CreateTdDate:input_type -> proto.TdDate
	16, // 41: proto.TdDateService.UpdateTdDate:input_type -> proto.TdDate
	19, // 42: proto.TdDateService.DeleteTdDate:input_type -> proto.TdDateIDIn
	23, // 43: proto.EmailReminderService.GetEmailReminder:input_type -> proto.EmailReminderIDIn
	20, // 44: proto.EmailReminderService.SearchEmailReminder:input_type -> proto.EmailReminder
	20, // 45: proto.EmailReminderService.CreateEmailReminder:input_type -> proto.EmailReminder
	20, // 46: proto.EmailReminderService.UpdateEmailReminder:input_type -> proto.EmailReminder
	23, // 47: proto.EmailReminderService.DeleteEmailReminder:input_type -> proto.EmailReminderIDIn
	3,  // 48: proto.RoleService.GetRole:output_type -> proto.RoleResponse
	4,  // 49: proto.RoleService.SearchRole:output_type -> proto.RoleRepeatResponse
	3,  // 50: proto.RoleService.CreateRole:output_type -> proto.RoleResponse
	1,  // 51: proto.RoleService.UpdateRole:output_type -> proto.Result
	1,  // 52: proto.RoleService.DeleteRole:output_type -> proto.Result
	7,  // 53: proto.LoginService.GetLogin:output_type -> proto.LoginResponse
	8,  // 54: proto.LoginService.SearchLogin:output_type -> proto.LoginRepeatResponse
	7,  // 55: proto.LoginService.CreateLogin:output_type -> proto.LoginResponse
	1,  // 56: proto.LoginService.UpdateLogin:output_type -> proto.Result
	1,  // 57: proto.LoginService.DeleteLogin:output_type -> proto.Result
	12, // 58: proto.LoginRoleService.GetLoginRole:output_type -> proto.LoginRoleResponse
	14, // 59: proto.LoginRoleService.SearchLoginRole:output_type -> proto.LoginRoleRepeatResponse
	12, // 60: proto.LoginRoleService.CreateLoginRole:output_type -> proto.LoginRoleResponse
	13, // 61: proto.LoginRoleService.BulkLoginRole:output_type -> proto.LoginRoleUpdateResponse
	1,  // 62: proto.LoginRoleService.UpdateLoginRole:output_type -> proto.Result
	1,  // 63: proto.LoginRoleService.DeleteLoginRole:output_type -> proto.Result
	17, // 64: proto.TdDateService.GetTdDate:output_type -> proto.TdDateResponse
	18, // 65: proto.TdDateService.SearchTdDate:output_type -> proto.TdDateRepeatResponse
	17, // 66: proto.TdDateService.CreateTdDate:output_type -> proto.TdDateResponse
	1,  // 67: proto.TdDateService.UpdateTdDate:output_type -> proto.Result
	1,  // 68: proto.TdDateService.DeleteTdDate:output_type -> proto.Result
	21, // 69: proto.EmailReminderService.GetEmailReminder:output_type -> proto.EmailReminderResponse
	22, // 70: proto.EmailReminderService.SearchEmailReminder:output_type -> proto.EmailReminderRepeatResponse
	21, // 71: proto.EmailReminderService.CreateEmailReminder:output_type -> proto.EmailReminderResponse
	1,  // 72: proto.EmailReminderService.UpdateEmailReminder:output_type -> proto.Result
	1,  // 73: proto.EmailReminderService.DeleteEmailReminder:output_type -> proto.Result
	48, // [48:74] is the sub-list for method output_type
	22, // [22:48] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_pkg_proto_tithe_declare_proto_init() }
func file_pkg_proto_tithe_declare_proto_init() {
	if File_pkg_proto_tithe_declare_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_tithe_declare_proto_rawDesc), len(file_pkg_proto_tithe_declare_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_pkg_proto_tithe_declare_proto_goTypes,
		DependencyIndexes: file_pkg_proto_tithe_declare_proto_depIdxs,
		MessageInfos:      file_pkg_proto_tithe_declare_proto_msgTypes,
	}.Build()
	File_pkg_proto_tithe_declare_proto = out.File
	file_pkg_proto_tithe_declare_proto_goTypes = nil
	file_pkg_proto_tithe_declare_proto_depIdxs = nil
}
